<?xml version="1.0" encoding="UTF-8"?>
<test-data
    xmlns="http://pmd.sourceforge.net/rule-tests"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://pmd.sourceforge.net/rule-tests http://pmd.sourceforge.net/rule-tests_1_0_0.xsd">

    <test-code>
        <description>Failure case: Empty Catch Block</description>
        <expected-problems>1</expected-problems>
        <code><![CDATA[
public class Foo {
    public void bar() {
        try {
            system.debug(1);
        } catch(Exception e) {
        }
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>Success case: Empty Catch Block</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Foo {
    public void foo() {
        try {
            system.debug(1);
        } catch(Exception e) {
            system.debug(e);
        }
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>#3569 - Verify use of reportInTestMethod, negative test unspecified/default</description>
        <expected-problems>2</expected-problems>
        <code><![CDATA[
@IsTest
private class FunctionalityTest {
    static testMethod void testWithModifier() {
        try {
            doSomethingThatShouldThrowAnException();
            System.assert(false, 'Expected an exception to be thrown.');
        } catch (Exception e) {
            // Expected
        }
    }

    @IsTest
    static void testWithAnnotation() {
        try {
            doSomethingThatShouldThrowAnException();
            System.assert(false, 'Expected an exception to be thrown.');
        } catch (Exception e) {
            // Expected
        }
    }
}
]]></code>
    </test-code>

    <test-code>
        <description>#3569 - Verify use of reportInTestMethod, negative test specified</description>
        <rule-property name="reportInTestMethod">true</rule-property>
        <expected-problems>2</expected-problems>
        <code><![CDATA[
@IsTest
private class FunctionalityTest {
    static testMethod void testWithModifier() {
        try {
            doSomethingThatShouldThrowAnException();
            System.assert(false, 'Expected an exception to be thrown.');
        } catch (Exception e) {
            // Expected
        }
    }

    @IsTest
    static void testWithAnnotation() {
        try {
            doSomethingThatShouldThrowAnException();
            System.assert(false, 'Expected an exception to be thrown.');
        } catch (Exception e) {
            // Expected
        }
    }
}
]]></code>
    </test-code>

    <test-code>
        <description>#3569 - Verify use of reportInTestMethod, positive test</description>
        <rule-property name="reportInTestMethod">false</rule-property>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
@IsTest
private class FunctionalityTest {
    static testMethod void testWithModifier() {
        try {
            doSomethingThatShouldThrowAnException();
            System.assert(false, 'Expected an exception to be thrown.');
        } catch (Exception e) {
            // Expected
        }
    }

    @IsTest
    static void testWithAnnotation() {
        try {
            doSomethingThatShouldThrowAnException();
            System.assert(false, 'Expected an exception to be thrown.');
        } catch (Exception e) {
            // Expected
        }
    }
}
]]></code>
    </test-code>
</test-data>
